CREATE TABLE IF NOT EXISTS `vehicles` (
  `name` varchar(60) NOT NULL,
  `model` varchar(60) NOT NULL,
  `price` int(11) NOT NULL,
  `category` varchar(60) DEFAULT NULL,
  `imglink` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`model`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

REPLACE INTO `vehicles` (`name`, `model`, `price`, `category`, `imglink`) VALUES
	('Akuma', 'akuma', 250000, 'cmotorcycles', 'https://imgur.com/45jGSHs.png'),
	('Asterope', 'asterope', 75000, 'csuper', 'https://imgur.com/XTTXBtM.png'),
	('Avarus', 'avarus', 50000, 'cmotorcycles', 'https://imgur.com/dBBcwQ1.png'),
	('Bagger', 'bagger', 100000, 'cmotorcycles', 'https://imgur.com/iZAt4G8.png'),
	('Baller', 'baller', 50000, 'isuvs', 'https://imgur.com/kGJuWdb.png'),
	('Baller 2', 'baller2', 300000, 'isuvs', 'https://imgur.com/2uYNgMx.png'),
	('Baller 4', 'baller4', 350000, 'isuvs', 'https://imgur.com/7dLAkl6.png'),
	('Bati', 'bati', 50000, 'cmotorcycles', 'https://imgur.com/86K42yH.png'),
	('Bestiagts', 'bestiagts', 500000, 'gsports', 'https://imgur.com/2apqPVW.png'),
	('Bf 400', 'bf400', 250000, 'cmotorcycles', 'https://imgur.com/dh4ATIN.png'),
	('Bfinjection', 'bfinjection', 40000, 'foffroad', 'https://imgur.com/hrInVRP.png'),
	('Bifta', 'bifta', 150000, 'foffroad', 'https://imgur.com/BG8SnzE.png'),
	('Bjxl', 'bjxl', 40000, 'isuvs', 'https://imgur.com/cNLC57c.png'),
	('Blade', 'blade', 250000, 'dmuscle', 'https://imgur.com/vdMNMYO.png'),
	('Blazer', 'blazer', 50000, 'foffroad', 'https://imgur.com/VMATCUH.png'),
	('Blazer 4', 'blazer4', 100000, 'foffroad', 'https://imgur.com/B8muCJc.png'),
	('Blista', 'blista', 15000, 'acompacts', 'https://imgur.com/btYPlq2.png'),
	('Brawler', 'brawler', 200000, 'foffroad', 'https://imgur.com/H7lakNa.png'),
	('Brioso', 'brioso', 14500, 'acompacts', 'https://imgur.com/usL3aMP.png'),
	('Btype', 'btype', 40000, 'hsportsclassics', 'https://imgur.com/wSQimvT.png'),
	('Btype 2', 'btype2', 150000, 'hsportsclassics', 'https://imgur.com/exxP4ti.png'),
	('Btype 3', 'btype3', 100000, 'hsportsclassics', 'https://imgur.com/caIVQ5N.png'),
	('Burrito', 'burrito', 200000, 'vans', 'https://imgur.com/1J92Yck.png'),
	('Burrito 3', 'burrito3', 200000, 'vans', 'https://imgur.com/PEJnzod.png'),
	('Caddy 1', 'caddy', 3000, 'acompacts', 'https://imgur.com/msXyruD.png'),
	('Caddy 2', 'caddy2', 3000, 'acompacts', 'https://imgur.com/shrZ7Wd.png'),
	('Carbonizzare', 'carbonizzare', 500000, 'gsports', 'https://imgur.com/Xh9qlYS.png'),
	('Casco', 'casco', 450000, 'hsportsclassics', 'https://imgur.com/lDMkNJz.png'),
	('Cheburek', 'cheburek', 120000, 'hsportsclassics', 'https://imgur.com/dp465WO.png'),
	('Chino 2', 'chino2', 100000, 'dmuscle', 'https://imgur.com/jUEh7kK.png'),
	('Cognoscenti 2', 'cognoscenti2', 350000, 'csuper', 'https://imgur.com/FHRF3UH.png'),
	('Coquette', 'coquette', 750000, 'gsports', 'https://imgur.com/vCpYFbE.png'),
	('Coquette2', 'coquette2', 800000, 'hsportsclassics', 'https://imgur.com/wUgtiq6.png'),
	('Deviant', 'deviant', 350000, 'dmuscle', 'https://imgur.com/C8WOtRY.png'),
	('Dilettante', 'dilettante', 12500, 'acompacts', 'https://imgur.com/YZrJJVi.png'),
	('Dominator 3', 'dominator3', 350000, 'dmuscle', 'https://imgur.com/6IBXE5u.png'),
	('Dubsta', 'dubsta', 100000, 'isuvs', 'https://imgur.com/y15RqlU.png'),
	('Dukes', 'dukes', 400000, 'dmuscle', 'https://imgur.com/OYlNc93.png'),
	('Elegy 2', 'elegy2', 500000, 'gsports', 'https://imgur.com/YUrpAVa.png'),
	('Exemplar', 'exemplar', 750000, 'gcoupes', 'https://imgur.com/t3CzkoA.png'),
	('F620', 'f620', 850000, 'gcoupes', 'https://imgur.com/aAXVOIF.png'),
	('Faction 2', 'faction2', 250000, 'dmuscle', 'https://imgur.com/dkJaHCg.png'),
	('Fagaloa', 'fagaloa', 100000, 'hsportsclassics', 'https://imgur.com/3E91QEz.png'),
	('Faggio', 'faggio', 2500, 'cmotorcycles', 'https://imgur.com/b2LzQRl.png'),
	('Faggio 2', 'faggio2', 2500, 'cmotorcycles', 'https://imgur.com/yUIRhJy.png'),
	('Faggio 3', 'faggio3', 2500, 'cmotorcycles', 'https://imgur.com/7uiRKrv.png'),
	('Felon 2', 'felon2', 175000, 'gcoupes', 'https://imgur.com/I7UG6Lx.png'),
	('Feltze r2', 'feltzer2', 500000, 'gsports', 'https://imgur.com/18YEiDQ.png'),
	('Feltze r3', 'feltzer3', 750000, 'hsportsclassics', 'https://imgur.com/GB7QqOs.png'),
	('Fq2', 'fq2', 10000, 'isuvs', 'https://imgur.com/3A2Y9ds.png'),
	('Granger', 'granger', 50000, 'isuvs', 'https://imgur.com/HzOwkjD.png'),
	('Gresley', 'gresley', 40000, 'isuvs', 'https://imgur.com/aSAFKAA.png'),
	('Gt500', 'gt500', 100000, 'hsportsclassics', 'https://imgur.com/1dfoBdU.png'),
	('Habanero', 'habanero', 150000, 'isuvs', 'https://imgur.com/f7Dbxml.png'),
	('Hotknife', 'hotknife', 300000, 'dmuscle', 'https://imgur.com/FtL0Kcy.png'),
	('Huntley', 'huntley', 300000, 'isuvs', 'https://imgur.com/D2cUEoo.png'),
	('Intruder', 'intruder', 150000, 'csuper', 'https://imgur.com/7ZgmvHD.png'),
	('Issi2', 'issi2', 35000, 'acompacts', 'https://imgur.com/kfZmoPa.png'),
	('Issi3', 'issi3', 25000, 'acompacts', 'https://imgur.com/A0CtQFc.png'),
	('Jackal', 'jackal', 150000, 'gcoupes', 'https://imgur.com/PKDyDcV.png'),
	('Jester 3', 'jester3', 750000, 'hsportsclassics', 'https://imgur.com/6yqCBSz.png'),
	('Kuruma', 'kuruma', 450000, 'gsports', 'https://imgur.com/CSuClgm.png'),
	('Lynx', 'lynx', 750000, 'gsports', 'https://imgur.com/IVoNqjp.png'),
	('Mamba', 'mamba', 635000, 'hsportsclassics', 'https://imgur.com/MaYzhdo.png'),
	('Mesa', 'mesa', 40000, 'isuvs', 'https://imgur.com/EFYu77H.png'),
	('Mesa 3', 'mesa3', 150000, 'foffroad', 'https://imgur.com/JM4uN2i.png'),
	('Minivan', 'minivan', 150000, 'sedans', 'https://imgur.com/XKiY20R.png'),
	('Nightshade', 'nightshade', 400000, 'dmuscle', 'https://imgur.com/Ffmqnuf.png'),
	('Oracle', 'oracle', 360000, 'gcoupes', 'https://imgur.com/ZCBq9Fh.png'),
	('Pariah', 'pariah', 1000000, 'gsports', 'https://imgur.com/adGX3SJ.png'),
	('Patriot', 'patriot', 40000, 'isuvs', 'https://imgur.com/osR7Aka.png'),
	('Phoenix', 'phoenix', 300000, 'dmuscle', 'https://imgur.com/uXvaRpX.png'),
	('Picador', 'picador', 250000, 'dmuscle', 'https://imgur.com/h3S2mzs.png'),
	('Prairie', 'prairie', 200000, 'csuper', 'https://imgur.com/nWxeSiK.png'),
	('Primo 2', 'primo2', 75000, 'csuper', 'https://imgur.com/lSv2oHi.png'),
	('Rapidgt', 'rapidgt', 500000, 'gsports', 'https://imgur.com/DqLdKwQ.png'),
	('Rapidgt 3', 'rapidgt3', 750000, 'hsportsclassics', 'https://imgur.com/RXOznlp.png'),
	('Rebel', 'rebel', 150000, 'foffroad', 'https://imgur.com/Z3rqT9G.png'),
	('Retinue', 'retinue', 750000, 'hsportsclassics', 'https://imgur.com/vSqkuHf.png'),
	('Rhapsody', 'rhapsody', 150000, 'csuper', 'https://imgur.com/wA0pXHi.png'),
	('Ruiner 2', 'ruiner2', 350000, 'dmuscle', 'https://imgur.com/xJIx0D1.png'),
	('Schafter 2', 'schafter2', 350000, 'csuper', 'https://imgur.com/wKlJNyW.png'),
	('Schlagen', 'schlagen', 1000000, 'gsports', 'https://imgur.com/NI0ewPn.png'),
	('Sentinel', 'sentinel', 125000, 'gcoupes', 'https://imgur.com/6ITgQjM.png'),
	('Serrano', 'serrano', 50000, 'isuvs', 'https://imgur.com/990Kjt5.png'),
	('Specter 2', 'specter2', 450000, 'gsports', 'https://imgur.com/7C8yz4L.png'),
	('Speedo 4', 'speedo4', 200000, 'vans', 'https://imgur.com/tQarosi.png'),
	('Stanier', 'stanier', 35000, 'csuper', 'https://imgur.com/Y3msXWK.png'),
	('Stinger', 'stinger', 950000, 'hsportsclassics', 'https://imgur.com/Rmf86ET.png'),
	('Stingergt', 'stingergt', 650000, 'hsportsclassics', 'https://imgur.com/XCiPoIw.png'),
	('Stratum', 'stratum', 50000, 'csuper', 'https://imgur.com/RHJaAee.png'),
	('Surano', 'surano', 750000, 'gsports', 'https://imgur.com/FiJihk7.png'),
	('Swinger', 'swinger', 600000, 'hsportsclassics', 'https://imgur.com/PHo8M37.png'),
	('Tampa', 'tampa', 400000, 'dmuscle', 'https://imgur.com/a70H8X7.png'),
	('Toros', 'toros', 500000, 'isuvs', 'https://imgur.com/aDPrcJn.png'),
	('Tulip', 'tulip', 600000, 'dmuscle', 'https://imgur.com/jcJ9etE.png'),
	('Verlierer 2', 'verlierer2', 650000, 'gsports', 'https://imgur.com/jVhItPr.png'),
	('Windsor', 'windsor', 500000, 'gcoupes', 'https://imgur.com/SDCOVCf.png'),
	('Windsor 2', 'windsor2', 650000, 'gcoupes', 'https://imgur.com/EBuDFFN.png'),
	('XLS', 'xls', 150000, 'isuvs', 'https://imgur.com/ErNSTbW.png'),
	('Youga', 'youga', 175000, 'vans', 'https://imgur.com/AgWu0ei.png'),
	('Youga 2', 'youga2', 200000, 'vans', 'https://imgur.com/ubr7lHX.png'),
	('z190', 'z190', 550000, 'hsportsclassics', 'https://imgur.com/2rvMEXX.png'),
	('zion', 'zion', 200000, 'gcoupes', 'https://imgur.com/fjk4zG9.png'),
	('zion2', 'zion2', 850000, 'gcoupes', 'https://imgur.com/VeWPhzF.png');

CREATE TABLE IF NOT EXISTS `vehicles_for_sale` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `seller` varchar(50) NOT NULL,
  `vehicleProps` longtext NOT NULL,
  `price` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `vehicle_categories` (
  `name` varchar(60) NOT NULL,
  `label` varchar(60) NOT NULL,
  PRIMARY KEY (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

REPLACE INTO `vehicle_categories` (`name`, `label`) VALUES
	('acompacts', 'Car starter'),
	('bcycle', 'Bike'),
	('cmotorcycles', 'Motorcycle'),
	('csuper', 'General car | 25 KG'),
	('dmuscle', 'Classic car | 25 KG'),
	('foffroad', 'Off - Road | 25 KG'),
	('gcoupes', 'Rich - car | 25 KG'),
	('gsports', 'Sports - car | 25 KG'),
	('hsportsclassics', 'Sports - classic | 25 KG'),
	('isuvs', 'Suvs - car | 30 KG'),
	('sedans', 'Load - car | 40 KG'),
	('vans', 'Truck - car | 50 KG');

CREATE TABLE IF NOT EXISTS `vehicle_sold` (
  `client` varchar(50) COLLATE utf8mb4_bin NOT NULL,
  `model` varchar(50) COLLATE utf8mb4_bin NOT NULL,
  `plate` varchar(50) COLLATE utf8mb4_bin NOT NULL,
  `soldby` varchar(50) COLLATE utf8mb4_bin NOT NULL,
  `date` varchar(50) COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`plate`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPACT;


CREATE TABLE IF NOT EXISTS `vehicle_soldout` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner` varchar(50) NOT NULL,
  `vehicle` longtext NOT NULL,
  `plate` varchar(50) NOT NULL,
  `date` varchar(50) NOT NULL,
  `price` int(11) NOT NULL,
  PRIMARY KEY (`id`,`plate`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

